travis:
  secure:
    BINSTAR_TOKEN: zUaX20zJf2i01PQpmB2sTFXd/3VnAJze5asQApKnbjCPdCIbDMWbqhOJnVKsFt8OMVvwUjNx/QHV/19Q0wtgr9H7eED6JsKcoYyypeDlwUz7Dlxn0TaD2ZzE87qPJs/Eyc55loCHVIzHHHW0OqAQgjKCSEhDUbU18i1WAJrqkzBO4xehzKpbX3pFkQrdT2M/fNS4m6qsbeU2WSLvVqdnuDY5ZUwn47XqKx+xAA1pO+vFLBnW8AfmGjBBbCl/6L1FXrgbp7qnS/qwkKzt42xztkkAB3rKLzFBLB09ORIRVOFWijM9owkpFf3B8LYYFYua9fxO0Hm8pTcPAHN0xjD8ChYskTozp3dULkt4WK9j7ATs+Z5epUk2wUSahkZJv2OfKPUnn8mSsBjHiITUX66Mi/Mtx4jCGzBbpZHV89ZyDNPo8fOCAJAm1h8gaElzzZu6uNkZ/q/DB9gH8xH9bGybWlRJiSNQYgfnmv5Q7EYRkjXN+hu/Km87lb6SXt2lPLNwjgU6G4OoBU5VYf6ZooA70bcAthVM4vtSLixUsE1s3JMGFxhmUWcZYgg4nSGHFpYsN6yCN2RzJERkCPEQQmTUxB3wDjAnmkJA3SPfu0H8FrDiUq9W6KX2Soy8Iw2NqwJNEefmwkwTdcseZyGQXE/Uk9nsnY2e5hQ1NvQTzv3fVd4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
